package com.drzenovka.cyhmn;

import net.minecraft.util.EnumChatFormatting;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.event.FMLServerStoppingEvent;

@Mod(modid = "cyhmn", version = "1.0.1", name = "CanYouHearMeNow")
public class CanYouHearMeNow {

    public static ChatRangeSettings chatSettings;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        chatSettings = new ChatRangeSettings(event.getSuggestedConfigurationFile());

        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = "Can You Hear Me Now";
        event.getModMetadata().credits = EnumChatFormatting.GOLD + "DrZenovka";
        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(EnumChatFormatting.GOLD + "DrZenovka");
        event.getModMetadata().authorList.add(EnumChatFormatting.GRAY + "LOGOS");
        event.getModMetadata().url = "https://github.com/donzilzenovka/CanYouHearMeNow";
        event.getModMetadata().description = EnumChatFormatting.GRAY
            + "A Minecraft mod that limits chat to a distance.";

        net.minecraftforge.common.MinecraftForge.EVENT_BUS.register(new ChatHandler());
    }

    @EventHandler
    public void serverStarting(FMLServerStartingEvent event) {
        event.registerServerCommand(new CommandCyhmn());
    }

    public static void reloadChatSettings() {
        if (chatSettings != null) {
            chatSettings.load(); // reload the config
        }
    }

    @EventHandler
    public void serverStopping(FMLServerStoppingEvent event) {
        // nothing special needed now
    }
}
