package com.drzenovka.cyhmn;

import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.nio.file.StandardWatchEventKinds;
import java.nio.file.WatchEvent;
import java.nio.file.WatchKey;
import java.nio.file.WatchService;

import net.minecraft.util.EnumChatFormatting;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.event.FMLServerStoppingEvent;

@Mod(modid = "cyhmn", version = "1.0.2", name = "CanYouHearMeNow")
public class CanYouHearMeNow {

    public static ChatRangeSettings chatSettings;
    private static Thread configWatcherThread;
    private static volatile boolean watcherRunning = false;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        chatSettings = new ChatRangeSettings(event.getSuggestedConfigurationFile());
        startConfigWatcher();

        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = "Can You Hear Me Now";
        event.getModMetadata().credits = EnumChatFormatting.GOLD + "DrZenovka";
        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(EnumChatFormatting.GOLD + "DrZenovka");
        event.getModMetadata().authorList.add(EnumChatFormatting.GRAY + "LOGOS");
        event.getModMetadata().url = "https://github.com/donzilzenovka/CanYouHearMeNow";
        event.getModMetadata().description = EnumChatFormatting.GRAY
            + "A Minecraft mod that limits chat to a distance.";

        net.minecraftforge.common.MinecraftForge.EVENT_BUS.register(new ChatHandler());
    }

    @EventHandler
    public void serverStarting(FMLServerStartingEvent event) {
        event.registerServerCommand(new CommandCyhmn());
    }

    public static void reloadChatSettings() {
        if (chatSettings != null) {
            chatSettings.load(); // always use load()
        }
    }

    private void startConfigWatcher() {
        if (watcherRunning) return;

        watcherRunning = true;
        configWatcherThread = new Thread(() -> {
            try {
                Path configPath = chatSettings.getConfigFile()
                    .toPath()
                    .getParent();
                WatchService watcher = FileSystems.getDefault()
                    .newWatchService();
                configPath.register(watcher, StandardWatchEventKinds.ENTRY_MODIFY);

                while (watcherRunning) {
                    WatchKey key = watcher.take();
                    for (WatchEvent<?> event : key.pollEvents()) {
                        Path changed = (Path) event.context();
                        if (changed.toString()
                            .equals(
                                chatSettings.getConfigFile()
                                    .getName())) {
                            chatSettings.load();
                            System.out.println("[CanYouHearMeNow] Config file changed, chat settings reloaded.");
                        }
                    }
                    key.reset();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        });
        configWatcherThread.setDaemon(true);
        configWatcherThread.start();
    }

    @EventHandler
    public void serverStopping(FMLServerStoppingEvent event) {
        watcherRunning = false;
    }
}
